# Generated by Django 5.2.7 on 2025-11-25 18:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),  # Ajusta si tu migración inicial tiene otro nombre
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='hora_inicio_preparacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora_fin_preparacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
