# Generated by Django 5.2.7 on 2025-11-26 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_horas_preparacion'),
        ('api', '0002_auto_20251103_1111'),
    ]

    operations = [
    ]
