# Generated by Django 5.2.7 on 2025-12-01 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productos_alter_pedido_estado_alter_pedido_mesa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='hora_fin_preparacion',
            new_name='tiempo_fin',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='hora_inicio_preparacion',
            new_name='tiempo_inicio',
        ),
        migrations.AddField(
            model_name='pedido',
            name='tiempo_preparacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('listo', 'Listo'), ('servido', 'Servido'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado'), ('retrasado', 'Retrasado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mesa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.mesero'),
        ),
    ]
